---
 - name: Download Zabbix Repository Ubuntu
   get_url: 
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu20.04_all.deb
    dest: /home/vagrant/zabbix-release_6.0-4+ubuntu20.04_all.deb
  
 - name: Install Zabbix Repository Ubuntu
   dpkg_selections:
    name: zabbix-release_6.0-4+ubuntu20.04_all.deb
    selection: install

 - name: Update SO Ubuntu
   apt:
    name: "*"
    update_cache: yes

 - name: Install Zabbix Agent Ubuntu
   apt:
    name: zabbix-agent
    state: latest
  
 - name: Copy template zabbix-agent.conf Ubuntu
   template:
    src: zabbix_agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

 - name: Start service
   service: name=zabbix-agent state=restarted  enabled=yes
...